### ISSUE TITLE
Fails with IndexError

### ISSUE THREAD

**Issue by andreas-globi** [benmoose39/ustvgo_to_m3u#18]
This started happening yesterday:

```
  0%|                                                                                                                         | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "ustvgo_m3ugrabber.py", line 93, in <module>
    grab(line)
  File "ustvgo_m3ugrabber.py", line 59, in grab
    getSample()
  File "ustvgo_m3ugrabber.py", line 49, in getSample
    novpn_sample = src.split("hls_src='")[1].split("'")[0]
IndexError: list index out of range
  1%|█▏                                                                                                               | 1/100 [00:22<36:20, 22.02s/it

```
The resulting m3u is empty

**Comment by Theitfixer85** [comment]
Not an error

As stated in the discord - you need a usa vpn

Check if it works on the ustvgo website
