### ISSUE TITLE
Ustvgo.tv is no more

### ISSUE THREAD

**Issue by pitsi** [benmoose39/ustvgo_to_m3u#27]
This reddit thread describes it better that I would ever do, so please read here
https://old.reddit.com/r/Piracy/comments/10hh1ff/ustvgo_says_sorry_we_are_closed/

I just read about it, I checked the script and it is not working
```
[*] Generating your playlist, please wait...

  0%|                                                   | 0/114 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/user/Desktop/ustvgo_to_m3u-main/scripts/ustvgo_m3ugrabber.py", line 89, in <module>
    grab(line)
  File "/home/user/Desktop/ustvgo_to_m3u-main/scripts/ustvgo_m3ugrabber.py", line 59, in grab
    getSample()
  File "/home/user/Desktop/ustvgo_to_m3u-main/scripts/ustvgo_m3ugrabber.py", line 49, in getSample
    novpn_sample = src.split("hls_src='")[1].split("'")[0]
IndexError: list index out of range
  1%|▍                                          | 1/114 [00:00<00:43,  2.60it/s]
```

**Comment by k0jam** [comment]
This one STILL stings!  It and Mobdro...
KODI I never cared for.  It got out of hand!

**Comment by pitsi** [comment]
Excuse me?
